name: yapim
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.8.6
  - pip
  - pip:
    - bcbio-gff==0.6.6
    - biopython==1.76
    - plumbum==1.6.6
    - networkx==2.2
    - pyyaml==5.3.1
    - art==5.1
    - pylint==2.6.0
    - pytest==6.2.1
    - pytest-cov==2.10.1
    - .