---  # document start

###########################################
## Global settings
GLOBAL:
  # Maximum threads/cpus to use in analysis
  MaxThreads: 10
  # Maximum memory to use (in GB)
  MaxMemory: 100

###########################################
## SLURM run settings
SLURM:
  ## Set to True if using SLURM
  USE_CLUSTER: false
  ## Pass any flags you wish below
  ## DO NOT PASS the following:
  ## --nodes, --ntasks, --mem, --cpus-per-task
  --qos: unlim
  --job-name: EukMS
  user-id: uid

###########################################
## Pipeline input section
INPUT:
  root: all

###########################################

IdentifyProteins:
  # Number of threads task will use
  threads: 1
  # Amount of memory task will use (in GB)
  memory: 8
  time: "4:00:00"
  program: prodigal
  FLAGS:
    -p meta

QualityCheck:
  # Number of threads task will use
  threads: 10
  # Amount of memory task will use (in GB)
  memory: 90
  time: "4:00:00"
  program: checkm
  min_quality: 60.0

CallAnnotate:
  # Number of threads task will use
  threads: 1
  # Amount of memory task will use (in GB)
  memory: 8
  time: "4:00:00"
  dependencies:
    Annotate:
      # Number of threads task will use
      threads: 5
      # Amount of memory task will use (in GB)
      memory: 30
      time: "4:00:00"
      program: mmseqs
      data:
        /media/user/2TB/Data/mmseqs/pfam_db
      FLAGS:
        --cov-mode 0
        -s 5
        -c 0.3
        --split-memory-limit 20G

...  # document end