---  # document start

###########################################
## Global settings
GLOBAL:
  # Maximum threads/cpus to use in analysis
  MaxThreads: 20
  # Maximum memory to use (in GB)
  MaxMemory: 100

###########################################
## SLURM run settings
SLURM:
  ## Set to True if using SLURM
  USE_CLUSTER: false
  ## Pass any flags you wish below
  ## DO NOT PASS the following:
  ## --nodes, --ntasks, --mem, --cpus-per-task
  --qos: unlim
  --job-name: EukMS
  user-id: uid

###########################################
## Pipeline input section
INPUT:
  root: all

###########################################

TrimReads:
  # Number of threads task will use
  threads: 8
  # Amount of memory task will use (in GB)
  memory: 16
  time: "4:00:00"
  program: trimmomatic
  TRIM_FLAGS:
    "ILLUMINACLIP:TruSeq3-PE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36"

Assemble:
  # Number of threads task will use
  threads: 8
  # Amount of memory task will use (in GB)
  memory: 16
  time: "4:00:00"
  program: megahit

CatalogueReads:
  # Number of threads task will use
  threads: 1
  # Amount of memory task will use (in GB)
  memory: 8
  time: "4:00:00"
  program: concatenate.py

MapBackReads:
  # Number of threads task will use
  threads: 8
  # Amount of memory task will use (in GB)
  memory: 24
  time: "4:00:00"
  program: minimap2
  converter: sambamba
  FLAGS:
    -N 50

Bin:
  # Number of threads task will use
  threads: 6
  # Amount of memory task will use (in GB)
  memory: 16
  time: "4:00:00"
  program: vamb
  FLAGS:
    --minfasta 1000
    -z 0.95
    -s 30

QualityCheck:
  # Number of threads task will use
  threads: 16
  # Amount of memory task will use (in GB)
  memory: 60
  time: "4:00:00"
  program: checkm
  min_quality: 5.0

IdentifyProteins:
  # Number of threads task will use
  threads: 1
  # Amount of memory task will use (in GB)
  memory: 4
  time: "4:00:00"
  program: prodigal
  FLAGS:
    -p meta

...  # document end