#!/usr/bin/env python
import os
from importlib import import_module
from inspect import isclass
from pathlib import Path
from typing import Optional, List, Type

from plumbum import cli

from HPCBioPipe.utils.config_manager import ConfigManager
from HPCBioPipe.utils.config_manager_generator import ConfigManagerGenerator
from HPCBioPipe.utils.executor import Executor
from HPCBioPipe.utils.extension_loader import ExtensionLoader
from HPCBioPipe.utils.input_loader import InputLoader


class HPCBioPipe(cli.Application):
    """
    Create and run an HPCBioPipeline
    """
    VERSION = "0.1.0"

    def main(self, *args):
        if args:
            print("Unknown command {0!r}".format(args[0]))
            exit(1)
        if not self.nested_command:
            self.help()
            exit(1)


@HPCBioPipe.subcommand("config")
class HPCBioPipeConfigCreator(cli.Application):
    """
    Create configuration file for a pipeline
    """
    tasks_directory: str
    dependencies_directories: Optional[List[str]] = None
    config_path: Path

    @cli.switch(["-t", "--tasks"], str, mandatory=True)
    def set_tasks_dir(self, tasks_dir):
        """Path to directory of pipeline Task/AggregateTasks"""
        if not os.path.exists(tasks_dir) or not os.path.isdir(tasks_dir):
            print("Unable to find tasks directory")
            exit(1)
        self.tasks_directory = tasks_dir

    @cli.switch(["-d", "--dependencies"], str, list=True)
    def set_dependencies_directory(self, dependencies):
        """Path to directory of Task/AggregateTask dependencies"""
        for dependency in dependencies:
            if not os.path.exists(dependency) or not os.path.isdir(dependency):
                print("Unable to find dependencies directory")
                exit(1)
        self.dependencies_directories = dependencies

    @cli.switch(["-c", "--config"], str, mandatory=True)
    def set_config_path(self, config):
        """Path to configuration file"""
        self.config_path = Path(config).resolve()

    def main(self):
        ConfigManagerGenerator(self.tasks_directory, self.dependencies_directories).write(self.config_path)


def _get_loader(loader_name: str) -> Type[InputLoader]:
    current_dir = os.getcwd()
    os.chdir(os.path.dirname(loader_name))
    module = import_module(os.path.basename(os.path.splitext(loader_name)[0]))
    for attribute_name in dir(module):
        attribute = getattr(module, attribute_name)
        if isclass(attribute) and issubclass(attribute, InputLoader) and loader_name in attribute.__name__:
            os.chdir(current_dir)
            return attribute
    os.chdir(current_dir)
    print("Unable to import loader module")
    exit(1)


@HPCBioPipe.subcommand("run")
class HPCBioPipeRunner(cli.Application):
    """
    Run a pipeline
    """
    input_directory: Optional[Path] = None
    loader: Type[InputLoader] = ExtensionLoader
    config_path: Path
    output_directory: Optional[Path] = Path(os.getcwd()).joinpath("out")
    tasks_directory: str
    dependencies_directories: Optional[List[str]] = None
    display_status: bool = True

    @cli.switch(["-l", "--loader"], str)
    def set_loader(self, loader_name):
        """Path to custom loader class extending InputLoader"""
        if not os.path.exists(loader_name) or not os.path.isfile(loader_name):
            print("Unable to find loader")
            exit(1)
        self.loader = _get_loader(loader_name)

    @cli.switch(["-i", "--input"], str)
    def set_input(self, input_directory):
        """Path to input directory"""
        if not os.path.exists(input_directory) or not os.path.isdir(input_directory):
            print("Unable to locate input directory")
            exit(1)
        self.input_directory = input_directory

    @cli.switch(["-c", "--config"], str, mandatory=True)
    def set_config_path(self, config):
        """Path to configuration file"""
        if not os.path.exists(config) or not os.path.isfile(config):
            print("Unable to load config file")
            exit(1)
        self.config_path = Path(config).resolve()

    @cli.switch(["-o", "--output"], str)
    def set_output_dir(self, output):
        """Path to output directory, default is <current-dir>/out"""
        self.output_directory = Path(output).resolve()

    @cli.switch(["-t", "--tasks"], str, mandatory=True)
    def set_tasks_dir(self, tasks_dir):
        """Path to directory of pipeline Task/AggregateTasks"""
        if not os.path.exists(tasks_dir) or not os.path.isdir(tasks_dir):
            print("Unable to find tasks directory")
            exit(1)
        self.tasks_directory = tasks_dir

    @cli.switch(["-d", "--dependencies"], str, list=True)
    def set_dependencies_directory(self, dependencies):
        """Path to directory of Task/AggregateTask dependencies"""
        for dependency in dependencies:
            if not os.path.exists(dependency) or not os.path.isdir(dependency):
                print("Unable to find dependencies directory")
                exit(1)
        self.dependencies_directories = dependencies

    @cli.switch(["-s", "--silence"])
    def set_verbosity(self):
        """Do not display log statements to stdout"""
        self.display_status = False

    def main(self, *args):
        if self.loader.__name__ == ExtensionLoader.__name__:
            if self.input_directory is None:
                print("Must set input directory for default ExtensionLoader")
                exit(1)
            Executor(
                self.loader(self.input_directory, self.output_directory.joinpath(ConfigManager.STORAGE_DIR)),
                self.config_path,
                self.output_directory,
                self.tasks_directory,
                self.dependencies_directories,
                self.display_status
            ).run()
        else:
            Executor(
                self.loader(*args),
                self.config_path,
                self.output_directory,
                self.tasks_directory,
                self.dependencies_directories,
                self.display_status
            ).run()


if __name__ == "__main__":
    HPCBioPipe.run()
