name: YAPIM CI

on:
  push:
    branches:
      - main
      - development
    tags:
      - '*'

jobs:
  install:
    strategy:
      matrix:
        python-version:
          - 3.8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: s-weigand/setup-conda@v1
      - run: conda install -y -c bioconda mmseqs2
      - run: pip install git+https://github.com/cjneely10/YAPIM.git
  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Run tests and coverage
        run: |
          /run_tests.sh
