name: YAPIM CI

on:
  push:
    branches:
      - main
      - development
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8" ]
    steps:
      - uses: actions/checkout@v3
      - uses: s-weigand/setup-conda@v1
      - name: Install python dependencies
        run: |
          conda install -y -c bioconda mmseqs2
          pip install .
      - name: Run tests and coverage
        run: ./run_tests.sh
        shell: bash
