name: YAPIM CI

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup-conda
        uses: s-weigand/setup-conda@v1.0.7
  install:
